version: '3.8'

# Job Tracker Application with PostgreSQL database
# To start database only: docker compose up -d db
# To start database with Adminer (DB GUI): docker compose up -d db adminer

services:
  db:
    image: postgres:15-alpine
    container_name: job_tracker_db
    environment:
      POSTGRES_DB: ${DB_NAME:-job_tracker}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - job_tracker_db_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-job_tracker}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: job_tracker_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  job_tracker_db_data:
